/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PostTypeEnum = IDL.Variant({
  'audio' : IDL.Null,
  'text' : IDL.Null,
});
export const Time = IDL.Int;
export const Post = IDL.Record({
  'postType' : PostTypeEnum,
  'audioDuration' : IDL.Opt(IDL.Nat),
  'originalLanguage' : IDL.Text,
  'contentText' : IDL.Text,
  'authorName' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'createdTimestamp' : Time,
  'commentsCount' : IDL.Nat,
  'translationText' : IDL.Text,
  'likesCount' : IDL.Nat,
  'postId' : IDL.Text,
});
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'authorName' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addSamplePosts' : IDL.Func([], [], []),
  'createPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        PostTypeEnum,
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Text],
      [],
    ),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getPostsByType' : IDL.Func([PostTypeEnum], [IDL.Vec(Post)], ['query']),
  'likePost' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PostTypeEnum = IDL.Variant({ 'audio' : IDL.Null, 'text' : IDL.Null });
  const Time = IDL.Int;
  const Post = IDL.Record({
    'postType' : PostTypeEnum,
    'audioDuration' : IDL.Opt(IDL.Nat),
    'originalLanguage' : IDL.Text,
    'contentText' : IDL.Text,
    'authorName' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'createdTimestamp' : Time,
    'commentsCount' : IDL.Nat,
    'translationText' : IDL.Text,
    'likesCount' : IDL.Nat,
    'postId' : IDL.Text,
  });
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'authorName' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addSamplePosts' : IDL.Func([], [], []),
    'createPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          PostTypeEnum,
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Text],
        [],
      ),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getPostsByType' : IDL.Func([PostTypeEnum], [IDL.Vec(Post)], ['query']),
    'likePost' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };